### ISSUE TITLE
Kernel offset in BoardConfig.mk should be 0x00008000

### ISSUE THREAD

**Issue by RankoR** [pix106/android_device_lenovo_Tab2A710F#4]
If it's default (not 0x-prefixed), build process raises error:
`mkbootimg: error: argument --kernel_offset: invalid parse_int value: '00008000'`

**Comment by pix106** [comment]
Thanks for your report.
It actually builds fine this way using omnirom 5.1 sources.
When i tried building using newer omnirom 7.1, 0x prifix is needed, indeed.
As 0x prefix builds fine with 5.1, i'll change it.
